apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-app-deployment
spec:
  selector:
    matchLabels:
      app: health-app
  replicas: 2
  template:
    metadata:
      labels:
        app: health-app
    spec:
      containers:
        - name: health-app
          image: saranshvijayvargiya/health-app:latest # Docker Hub image name
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082 # Port exposed by the container as per the Dockerfile

---
apiVersion: v1
kind: Service
metadata:
  name: health-app-service
spec:
  selector:
    app: health-app
  ports:
    - protocol: TCP
      port: 8080 # Port exposed by the service within the cluster
      targetPort: 8082 # Port on the container to route traffic to (from the Dockerfile)
  type: NodePort
