apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: saranshvijayvargiya/app:latest  # Replace with your image
          ports:
            - containerPort: 8082  # The port your application listens to
          env:
            - name: JAVA_OPTS
              value: "-Dserver.port=8082"  # Optional: Set custom JAVA_OPTS if needed

---
apiVersion: v1
kind: Service
metadata:
  name: app-svc
spec:
  type: NodePort
  selector:
    app: app
  ports:
    - port: 8082        # The port exposed within the cluster
      targetPort: 8082   # Forward traffic to container's port 8082
      nodePort: 30080    # Expose the service on NodePort 30080 (or change it)
