apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-care-project-deployment
  labels:
    app: health-care-project
spec:
  replicas: 3
  selector:
    matchLabels:
      app: health-care-project
  template:
    metadata:
      labels:
        app: health-care-project
    spec:
      containers:
      - name: health-care-project
        image: saranshvijayvargiya/health-care-project
        ports:
        - containerPort: 3000
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: health-care-projectsvc
spec:
  selector:
    app: health-care-project
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 8082
